### ISSUE TITLE
PyPI package name

### ISSUE THREAD

**Issue by vmagamedov** [chbrown/pi#1]
Hello! I have a project (https://github.com/vmagamedov/pi) with the same name as this project. As I can see, your project is not active. If this is true, would you mind to give me that name on PyPI?

**Comment by vmagamedov** [comment]
@chbrown ping^

**Comment by chbrown** [comment]
Sorry for the long silence. Every time I have to use `pip` I still dream about getting back to my rewrite, then quickly get lost / scared at how deep the Python packaging rabbit hole goes.

My `pi` package did add a bit of (admittedly hack-ish) functionality to setuptools, and there might be some system out there that uses it for some legacy reason, and depends on getting it from PyPI. I highly doubt it, but it's a possibility, and in general it's bad practice to replace, wholesale, a project on a public / permanent artifact repository (like PyPI) with one that is totally different.

So I'd like to hang onto the name for now, though if your project becomes immensely popular in the future and has good reason to need the `pi` name, I would reconsider.

**Comment by vmagamedov** [comment]
Thank you for reply, sounds reasonable.
